language: python
python:
  - 3.5
  - 3.6

# For Python 3.7
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

script: 
  - python setup.py install
  - python test.py
